/**
 * Service cities beyond Lahore, and a real catalog for each one.
 *
 * Every city gets the four store types a customer expects to find on day one —
 * a signature local restaurant, a second restaurant/cafe, a grocery mart and a
 * pharmacy — with menus written around what that city is actually known for
 * (sajji in Quetta, chapli kabab in Peshawar, pulao in Islamabad, bun kabab and
 * biryani in Karachi). Prices follow local norms rather than Lahore's.
 */

import { IMG, p, SeedStore } from './seed-data';

export type SeedCity = {
  name: string;
  slug: string;
  province: string;
  lat: number;
  lng: number;
  radiusKm: number;
  baseDeliveryFee: number;
  perKmFee: number;
  minOrderAmount: number;
  etaBaseMin: number;
  etaPerKmMin: number;
  sortOrder: number;
};

/**
 * Radii and fees are tuned per city: Karachi is huge and spread out, Quetta is
 * compact. Islamabad and Rawalpindi sit ~13 km apart, so both are kept
 * deliberately tight — a wide radius would make a Pindi address resolve to
 * Islamabad and quietly show the wrong catalog.
 */
export const SERVICE_CITIES: SeedCity[] = [
  { name: 'Lahore', slug: 'lahore', province: 'Punjab', lat: 31.5204, lng: 74.3587, radiusKm: 30, baseDeliveryFee: 79, perKmFee: 12, minOrderAmount: 300, etaBaseMin: 20, etaPerKmMin: 2.5, sortOrder: 0 },
  { name: 'Karachi', slug: 'karachi', province: 'Sindh', lat: 24.8607, lng: 67.0011, radiusKm: 45, baseDeliveryFee: 89, perKmFee: 13, minOrderAmount: 350, etaBaseMin: 22, etaPerKmMin: 2.8, sortOrder: 1 },
  { name: 'Islamabad', slug: 'islamabad', province: 'Islamabad Capital Territory', lat: 33.6844, lng: 73.0479, radiusKm: 18, baseDeliveryFee: 99, perKmFee: 14, minOrderAmount: 400, etaBaseMin: 20, etaPerKmMin: 2.4, sortOrder: 2 },
  { name: 'Rawalpindi', slug: 'rawalpindi', province: 'Punjab', lat: 33.5651, lng: 73.0169, radiusKm: 16, baseDeliveryFee: 79, perKmFee: 12, minOrderAmount: 300, etaBaseMin: 20, etaPerKmMin: 2.5, sortOrder: 3 },
  { name: 'Peshawar', slug: 'peshawar', province: 'Khyber Pakhtunkhwa', lat: 34.0151, lng: 71.5249, radiusKm: 22, baseDeliveryFee: 79, perKmFee: 11, minOrderAmount: 300, etaBaseMin: 20, etaPerKmMin: 2.5, sortOrder: 4 },
  { name: 'Quetta', slug: 'quetta', province: 'Balochistan', lat: 30.1798, lng: 66.975, radiusKm: 18, baseDeliveryFee: 89, perKmFee: 13, minOrderAmount: 300, etaBaseMin: 25, etaPerKmMin: 2.8, sortOrder: 5 },
];

/** Grocery aisles are near-identical everywhere, so one builder covers all five marts. */
const groceryMenu = (priceShift = 0) => {
  const q = (n: number) => Math.round(n * (1 + priceShift));
  return [
    {
      name: 'Fruit & Vegetables',
      items: [
        p('Banana (1 dozen)', 'Sindhi bananas, ripened naturally.', q(220), IMG.banana, { isVeg: true, unit: 'dozen', isPopular: true }),
        p('Tomatoes', 'Firm red tomatoes for daily cooking.', q(120), IMG.tomatoes, { isVeg: true, unit: '1 kg' }),
        p('Onions', 'Everyday red onions.', q(110), IMG.onions, { isVeg: true, unit: '1 kg' }),
        p('Potatoes', 'Fresh white potatoes.', q(95), IMG.potatoes, { isVeg: true, unit: '1 kg' }),
        p('Apples (Kashmiri)', 'Crisp and sweet, hand-picked.', q(360), IMG.apple, { isVeg: true, unit: '1 kg' }),
      ],
    },
    {
      name: 'Dairy & Bakery',
      items: [
        p('Fresh Milk 1L', 'Pasteurised full-cream milk.', q(230), IMG.milk, { isVeg: true, unit: '1 litre', isPopular: true }),
        p('Eggs (1 dozen)', 'Farm-fresh brown eggs.', q(340), IMG.eggs, { unit: 'dozen' }),
        p('Yogurt 500g', 'Thick set dahi.', q(160), IMG.yogurt, { isVeg: true, unit: '500 g' }),
        p('Butter 200g', 'Salted dairy butter.', q(480), IMG.butter, { isVeg: true, unit: '200 g' }),
        p('Bakery Bread', 'Soft milk bread, baked this morning.', q(180), IMG.bread, { isVeg: true, unit: 'large loaf' }),
      ],
    },
    {
      name: 'Pantry Staples',
      items: [
        p('Basmati Rice 5kg', 'Extra-long grain aged basmati.', q(2650), IMG.rice, { isVeg: true, unit: '5 kg', isPopular: true }),
        p('Chakki Atta 10kg', 'Stone-ground whole wheat flour.', q(1450), IMG.atta, { isVeg: true, unit: '10 kg' }),
        p('Cooking Oil 5L', 'Refined canola cooking oil.', q(2850), IMG.oil, { isVeg: true, unit: '5 litre' }),
        p('Sugar 1kg', 'Refined white sugar.', q(185), IMG.sugar, { isVeg: true, unit: '1 kg' }),
        p('Chana Daal 1kg', 'Split chickpea lentils.', q(320), IMG.daal, { isVeg: true, unit: '1 kg' }),
        p('Tea (Danedar) 950g', 'Strong black tea for doodh patti.', q(1650), IMG.tea, { isVeg: true, unit: '950 g' }),
      ],
    },
    {
      name: 'Snacks & Drinks',
      items: [
        p('Soft Drink 1.5L', 'Chilled Coke, Sprite or Fanta.', q(200), IMG.soda, { isVeg: true }),
        p('Mineral Water 1.5L', 'Bottled drinking water.', q(90), IMG.juice, { isVeg: true }),
        p('Potato Crisps', 'Salted crisps, family pack.', q(150), IMG.chips, { isVeg: true }),
        p('Biscuits Family Pack', 'Assorted tea biscuits.', q(260), IMG.biscuits, { isVeg: true }),
      ],
    },
  ];
};

/** Same reasoning for pharmacies — the shelf is the shelf. */
const pharmacyMenu = () => [
  {
    name: 'Everyday Medicine',
    items: [
      p('Paracetamol 500mg (20 tabs)', 'For fever and mild pain relief.', 90, IMG.tablets, { unit: 'strip of 20', isPopular: true }),
      p('Ibuprofen 400mg (20 tabs)', 'Anti-inflammatory pain relief.', 160, IMG.tablets, { unit: 'strip of 20' }),
      p('Antacid Suspension 120ml', 'Relief from heartburn and acidity.', 210, IMG.syrup, { unit: '120 ml' }),
      p('ORS Sachets (6 pack)', 'Oral rehydration salts for dehydration.', 180, IMG.medicine, { unit: '6 sachets' }),
      p('Cough Syrup 120ml', 'Soothes dry and chesty cough.', 340, IMG.syrup, { unit: '120 ml' }),
    ],
  },
  {
    name: 'Vitamins & Supplements',
    items: [
      p('Vitamin C 1000mg (30 tabs)', 'Effervescent vitamin C tablets.', 620, IMG.vitamins, { unit: '30 tablets', isPopular: true }),
      p('Multivitamin (30 caps)', 'Daily multivitamin and mineral capsules.', 890, IMG.vitamins, { unit: '30 capsules' }),
      p('Calcium + D3 (30 tabs)', 'Bone health supplement.', 540, IMG.vitamins, { unit: '30 tablets' }),
      p('Iron Supplement (30 tabs)', 'For iron deficiency support.', 460, IMG.vitamins, { unit: '30 tablets' }),
    ],
  },
  {
    name: 'First Aid & Care',
    items: [
      p('Adhesive Bandages (20 pack)', 'Assorted sizes, waterproof.', 220, IMG.bandage, { unit: '20 strips' }),
      p('Antiseptic Liquid 250ml', 'For cuts, grazes and disinfecting.', 380, IMG.spray, { unit: '250 ml' }),
      p('Digital Thermometer', 'Fast-read digital thermometer.', 950, IMG.thermometer),
      p('Surgical Face Masks (50)', 'Three-ply disposable masks.', 420, IMG.mask, { unit: 'box of 50' }),
      p('Hand Sanitiser 500ml', '70% alcohol hand sanitiser.', 490, IMG.sanitizer, { unit: '500 ml' }),
    ],
  },
  {
    name: 'Baby & Personal Care',
    items: [
      p('Baby Diapers (Medium, 40)', 'Soft, absorbent day-and-night diapers.', 1750, IMG.diapers, { unit: 'pack of 40' }),
      p('Baby Wipes (72)', 'Fragrance-free cleansing wipes.', 390, IMG.wipes, { unit: 'pack of 72' }),
      p('Shampoo 400ml', 'Everyday anti-dandruff shampoo.', 780, IMG.lotion, { unit: '400 ml' }),
      p('Toothpaste 150g', 'Fluoride cavity protection.', 320, IMG.toothpaste, { unit: '150 g' }),
    ],
  },
];

export const CITY_STORES: SeedStore[] = [
  // ───────────────────────── Karachi ─────────────────────────
  {
    slug: 'khi-saddar-biryani-house',
    name: 'Saddar Biryani House',
    city: 'Karachi',
    category: 'RESTAURANTS',
    photo: 'photo-1563379091339-03b21ab4a4f8',
    rating: 4.7,
    ratingCount: 8420,
    deliveryTimeMin: 30,
    deliveryTimeMax: 45,
    deliveryFee: 89,
    minOrder: 350,
    distanceKm: 3.2,
    tags: ['Biryani', 'Karachi', 'Desi'],
    isOpen: true,
    promoLabel: 'Double raita free on family packs',
    area: 'Saddar',
    address: 'Preedy Street, Saddar, Karachi',
    lat: 24.8607,
    lng: 67.0225,
    ownerName: 'Kashif Siddiqui',
    ownerContact: '03211234501',
    menu: [
      {
        name: 'Biryani',
        items: [
          p('Chicken Biryani (Single)', 'Karachi-style spicy chicken biryani with aloo and a boiled egg.', 380, IMG.biryani, { isPopular: true }),
          p('Beef Biryani (Single)', 'Slow-cooked beef biryani, heavy on the masala.', 450, IMG.biryani2),
          p('Chicken Biryani Family Pack', 'Serves 4-5, with raita and salad.', 1650, IMG.biryani, { isPopular: true }),
          p('Sindhi Biryani (Single)', 'Extra tangy with plum and potato.', 420, IMG.biryani2),
          p('Plain Pulao', 'Mildly spiced yakhni pulao.', 320, IMG.pulao),
        ],
      },
      {
        name: 'BBQ & Kebab',
        items: [
          p('Chicken Boti (6 pcs)', 'Charcoal-grilled boneless chicken boti.', 620, IMG.tikka, { isPopular: true }),
          p('Beef Seekh Kebab (4 pcs)', 'Hand-minced beef seekh off the coals.', 560, IMG.seekh),
          p('Chicken Malai Boti', 'Creamy, mild and tender.', 680, IMG.bbq),
          p('Bihari Boti', 'Papaya-marinated beef bihari, a Karachi favourite.', 720, IMG.chops),
        ],
      },
      {
        name: 'Sides & Breads',
        items: [
          p('Raita', 'Cool mint and cucumber yogurt.', 80, IMG.yogurt, { isVeg: true }),
          p('Kachumber Salad', 'Onion, tomato, cucumber and lemon.', 90, IMG.spinach, { isVeg: true }),
          p('Roghni Naan', 'Sesame-topped naan.', 70, IMG.naan, { isVeg: true }),
          p('Paratha', 'Flaky fried paratha.', 110, IMG.paratha, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks & Sweets',
        items: [
          p('Kashmiri Chai', 'Pink salted tea with pistachio.', 220, IMG.chai, { isVeg: true, isPopular: true }),
          p('Lassi', 'Sweet or salted, served chilled.', 180, IMG.lassi, { isVeg: true }),
          p('Soft Drink 500ml', 'Chilled bottle.', 120, IMG.soda, { isVeg: true }),
          p('Gulab Jamun (4 pcs)', 'Warm, syrup-soaked.', 260, IMG.gulabJamun, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'khi-burns-road-bun-kabab',
    name: 'Burns Road Bun Kabab',
    city: 'Karachi',
    category: 'RESTAURANTS',
    photo: 'photo-1568901346375-23c9450c58cd',
    rating: 4.5,
    ratingCount: 3960,
    deliveryTimeMin: 20,
    deliveryTimeMax: 35,
    deliveryFee: 69,
    minOrder: 250,
    distanceKm: 2.4,
    tags: ['Bun Kabab', 'Street Food', 'Fast Food'],
    isOpen: true,
    area: 'Burns Road',
    address: 'Burns Road Food Street, Karachi',
    lat: 24.8656,
    lng: 67.0165,
    ownerName: 'Adnan Qureshi',
    ownerContact: '03211234502',
    menu: [
      {
        name: 'Bun Kabab',
        items: [
          p('Anda Bun Kabab', 'Shami patty, fried egg, chutney, toasted bun.', 220, IMG.burger, { isPopular: true }),
          p('Chicken Bun Kabab', 'Spiced chicken patty with imli chutney.', 250, IMG.burger2),
          p('Double Patty Bun Kabab', 'Two shami patties for a proper meal.', 340, IMG.burger, { isPopular: true }),
          p('Aloo Bun Kabab', 'Spiced potato patty.', 180, IMG.burger2, { isVeg: true }),
        ],
      },
      {
        name: 'Rolls & Fries',
        items: [
          p('Chicken Paratha Roll', 'Chicken tikka rolled in a flaky paratha.', 320, IMG.roll, { isPopular: true }),
          p('Beef Kabab Roll', 'Seekh kabab, onion and chutney.', 350, IMG.wrap),
          p('Masala Fries', 'Crisp fries tossed in chaat masala.', 200, IMG.fries, { isVeg: true }),
          p('Loaded Fries', 'Fries with chicken, cheese sauce and jalapeños.', 420, IMG.fries),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Doodh Soda', 'The Karachi classic — milk and 7Up.', 180, IMG.shake, { isVeg: true, isPopular: true }),
          p('Fresh Lime Soda', 'Sweet or salted.', 150, IMG.lemonade, { isVeg: true }),
          p('Soft Drink 500ml', 'Chilled bottle.', 120, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'khi-clifton-super-mart',
    name: 'Clifton Super Mart',
    city: 'Karachi',
    category: 'GROCERY',
    photo: 'photo-1601599561213-832382fd07ba',
    rating: 4.6,
    ratingCount: 2180,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 99,
    minOrder: 800,
    distanceKm: 4.1,
    tags: ['Grocery', 'Daily Needs', 'Fresh'],
    isOpen: true,
    promoLabel: 'Free delivery over Rs 3,000',
    area: 'Clifton Block 4',
    address: 'Zamzama Boulevard, Clifton Block 4, Karachi',
    lat: 24.8138,
    lng: 67.03,
    ownerName: 'Hina Mansoor',
    ownerContact: '03211234503',
    menu: groceryMenu(0.05),
  },
  {
    slug: 'khi-clifton-care-pharmacy',
    name: 'Clifton Care Pharmacy',
    city: 'Karachi',
    category: 'PHARMACY',
    photo: 'photo-1576602976047-174e57a47881',
    rating: 4.8,
    ratingCount: 1540,
    deliveryTimeMin: 20,
    deliveryTimeMax: 35,
    deliveryFee: 79,
    minOrder: 300,
    distanceKm: 2.9,
    tags: ['Pharmacy', 'Medicine', '24/7'],
    isOpen: true,
    area: 'Clifton Block 2',
    address: 'Main Clifton Road, Block 2, Karachi',
    lat: 24.818,
    lng: 67.0275,
    ownerName: 'Dr. Sameer Ali',
    ownerContact: '03211234504',
    menu: pharmacyMenu(),
  },

  // ───────────────────────── Islamabad ─────────────────────────
  {
    slug: 'isb-capital-pulao-house',
    name: 'Capital Pulao House',
    city: 'Islamabad',
    category: 'RESTAURANTS',
    photo: 'photo-1596797038530-2c107229654b',
    rating: 4.8,
    ratingCount: 6740,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 99,
    minOrder: 400,
    distanceKm: 2.8,
    tags: ['Pulao', 'Desi', 'Islamabad'],
    isOpen: true,
    promoLabel: 'Free kheer with every family deal',
    area: 'F-8 Markaz',
    address: 'Bhittai Road, F-8 Markaz, Islamabad',
    lat: 33.708,
    lng: 73.051,
    ownerName: 'Tariq Mehmood',
    ownerContact: '03331234501',
    menu: [
      {
        name: 'Pulao & Rice',
        items: [
          p('Chicken Pulao (Single)', 'The Islamabad classic — yakhni pulao with a chicken leg.', 420, IMG.pulao, { isPopular: true }),
          p('Beef Pulao (Single)', 'Tender beef shanks over aromatic rice.', 480, IMG.pulao),
          p('Kabuli Pulao', 'Carrots, raisins and almonds with soft beef.', 650, IMG.pulao, { isPopular: true }),
          p('Chicken Pulao Family Pack', 'Serves 4, with raita and salad.', 1750, IMG.rice),
          p('Plain Rice', 'Steamed basmati.', 220, IMG.rice, { isVeg: true }),
        ],
      },
      {
        name: 'Karahi & Handi',
        items: [
          p('Chicken Karahi (Half)', 'Fresh tomato karahi with green chilli.', 1150, IMG.karahi, { isPopular: true }),
          p('Mutton Karahi (Half)', 'Slow-cooked bone-in mutton.', 1850, IMG.curry),
          p('Chicken Handi', 'Creamy boneless handi.', 1290, IMG.handi),
          p('Daal Maash', 'Buttery white lentils with ginger.', 420, IMG.daal, { isVeg: true }),
        ],
      },
      {
        name: 'Breads & Sides',
        items: [
          p('Tandoori Roti', 'Straight from the tandoor.', 35, IMG.roti, { isVeg: true }),
          p('Garlic Naan', 'Brushed with garlic butter.', 90, IMG.naan, { isVeg: true }),
          p('Raita', 'Mint and cucumber yogurt.', 90, IMG.yogurt, { isVeg: true }),
          p('Salad', 'Fresh onion, tomato and lemon.', 90, IMG.spinach, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks & Dessert',
        items: [
          p('Kashmiri Chai', 'Pink tea with crushed pistachio.', 250, IMG.chai, { isVeg: true, isPopular: true }),
          p('Sweet Lassi', 'Thick lassi topped with malai.', 200, IMG.lassi, { isVeg: true }),
          p('Kheer', 'Slow-cooked rice pudding.', 240, IMG.kheer, { isVeg: true }),
          p('Soft Drink 1.5L', 'Coke, Sprite or Fanta.', 200, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'isb-margalla-afghan-kitchen',
    name: 'Margalla Afghan Kitchen',
    city: 'Islamabad',
    category: 'RESTAURANTS',
    photo: 'photo-1529042410759-befb1204b468',
    rating: 4.6,
    ratingCount: 2870,
    deliveryTimeMin: 30,
    deliveryTimeMax: 45,
    deliveryFee: 109,
    minOrder: 500,
    distanceKm: 3.6,
    tags: ['Afghan', 'BBQ', 'Karahi'],
    isOpen: true,
    area: 'F-10 Markaz',
    address: 'Jinnah Super adjacent, F-10 Markaz, Islamabad',
    lat: 33.6938,
    lng: 73.0125,
    ownerName: 'Gul Rahman',
    ownerContact: '03331234502',
    menu: [
      {
        name: 'Afghan Specials',
        items: [
          p('Kabuli Pulao (Full)', 'Serves 2-3, with lamb shank, carrot and raisin.', 1850, IMG.pulao, { isPopular: true }),
          p('Afghani Chicken Karahi', 'Mild, buttery karahi with black pepper.', 1450, IMG.karahi, { isPopular: true }),
          p('Lamb Chops (4 pcs)', 'Charcoal-grilled, lightly spiced.', 1650, IMG.chops),
          p('Chapli Kabab (2 pcs)', 'Peshawari-style minced beef kabab.', 620, IMG.seekh),
        ],
      },
      {
        name: 'From the Grill',
        items: [
          p('Chicken Tikka (2 pcs)', 'Charcoal tikka with lemon.', 520, IMG.tikka),
          p('Beef Seekh Kebab (4 pcs)', 'Hand-minced and grilled.', 590, IMG.seekh),
          p('Malai Boti', 'Creamy boneless chicken.', 690, IMG.bbq),
        ],
      },
      {
        name: 'Bread & Sides',
        items: [
          p('Afghani Naan', 'Long, sesame-topped tandoor bread.', 120, IMG.naan, { isVeg: true, isPopular: true }),
          p('Tandoori Roti', 'Fresh off the tandoor.', 35, IMG.roti, { isVeg: true }),
          p('Green Chutney', 'Mint, coriander and chilli.', 60, IMG.spinach, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Green Kahwa', 'Cardamom green tea.', 160, IMG.kahwa, { isVeg: true }),
          p('Doogh (Salted Lassi)', 'Chilled salted yogurt drink with mint.', 190, IMG.lassi, { isVeg: true }),
          p('Soft Drink 500ml', 'Chilled bottle.', 120, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'isb-blue-area-grocers',
    name: 'Blue Area Grocers',
    city: 'Islamabad',
    category: 'GROCERY',
    photo: 'photo-1601599561213-832382fd07ba',
    rating: 4.7,
    ratingCount: 1920,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 109,
    minOrder: 900,
    distanceKm: 3.4,
    tags: ['Grocery', 'Imported', 'Fresh'],
    isOpen: true,
    promoLabel: 'Free delivery over Rs 3,500',
    area: 'F-10 Markaz',
    address: 'Jinnah Super Market, F-10 Markaz, Islamabad',
    lat: 33.695,
    lng: 73.014,
    ownerName: 'Nadia Khan',
    ownerContact: '03331234503',
    menu: groceryMenu(0.08),
  },
  {
    slug: 'isb-capital-chemist',
    name: 'Capital Chemist',
    city: 'Islamabad',
    category: 'PHARMACY',
    photo: 'photo-1576602976047-174e57a47881',
    rating: 4.8,
    ratingCount: 1280,
    deliveryTimeMin: 20,
    deliveryTimeMax: 35,
    deliveryFee: 89,
    minOrder: 300,
    distanceKm: 2.5,
    tags: ['Pharmacy', 'Medicine', 'Wellness'],
    isOpen: true,
    area: 'F-7 Markaz',
    address: 'Bhittai Road, F-7 Markaz, Islamabad',
    lat: 33.719,
    lng: 73.056,
    ownerName: 'Dr. Ayesha Noor',
    ownerContact: '03331234504',
    menu: pharmacyMenu(),
  },

  // ───────────────────────── Rawalpindi ─────────────────────────
  {
    slug: 'rwp-saddar-tikka-house',
    name: 'Saddar Tikka House',
    city: 'Rawalpindi',
    category: 'RESTAURANTS',
    photo: 'photo-1599487488170-d11ec9c172f0',
    rating: 4.7,
    ratingCount: 4310,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 79,
    minOrder: 300,
    distanceKm: 2.2,
    tags: ['Tikka', 'BBQ', 'Desi'],
    isOpen: true,
    promoLabel: 'Buy 6 tikka, get 1 free',
    area: 'Saddar',
    address: 'Bank Road, Saddar, Rawalpindi',
    lat: 33.598,
    lng: 73.047,
    ownerName: 'Kaleem Abbas',
    ownerContact: '03451234501',
    menu: [
      {
        name: 'Charcoal BBQ',
        items: [
          p('Chicken Tikka (Leg)', 'Whole leg piece, marinated overnight.', 380, IMG.tikka, { isPopular: true }),
          p('Chicken Tikka (Breast)', 'Boneless-friendly breast piece.', 420, IMG.tikka),
          p('Beef Seekh Kebab (4 pcs)', 'Smoky hand-minced seekh.', 520, IMG.seekh, { isPopular: true }),
          p('Mutton Chops (4 pcs)', 'Tender chops off the coals.', 1450, IMG.chops),
          p('Chicken Malai Boti', 'Creamy and mild.', 650, IMG.bbq),
        ],
      },
      {
        name: 'Karahi & Handi',
        items: [
          p('Chicken Karahi (Half)', 'Tomato-heavy Pindi-style karahi.', 1050, IMG.karahi, { isPopular: true }),
          p('Mutton Karahi (Half)', 'Bone-in mutton, slow-cooked.', 1750, IMG.curry),
          p('Daal Fry', 'Tempered yellow lentils.', 350, IMG.daal, { isVeg: true }),
        ],
      },
      {
        name: 'Breads & Sides',
        items: [
          p('Tandoori Roti', 'Fresh tandoor roti.', 30, IMG.roti, { isVeg: true }),
          p('Garlic Naan', 'Garlic butter naan.', 80, IMG.naan, { isVeg: true }),
          p('Raita', 'Mint yogurt.', 80, IMG.yogurt, { isVeg: true }),
          p('Salad', 'Onion, tomato and lemon.', 80, IMG.spinach, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Doodh Patti Chai', 'Strong full-milk tea.', 120, IMG.chai, { isVeg: true, isPopular: true }),
          p('Sweet Lassi', 'Chilled and thick.', 170, IMG.lassi, { isVeg: true }),
          p('Soft Drink 1.5L', 'Coke, Sprite or Fanta.', 200, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'rwp-committee-chowk-nihari',
    name: 'Committee Chowk Nihari',
    city: 'Rawalpindi',
    category: 'RESTAURANTS',
    photo: 'photo-1574484284002-952d92456975',
    rating: 4.6,
    ratingCount: 2640,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 79,
    minOrder: 300,
    distanceKm: 2.8,
    tags: ['Nihari', 'Breakfast', 'Desi'],
    isOpen: true,
    area: 'Committee Chowk',
    address: 'Murree Road, Committee Chowk, Rawalpindi',
    lat: 33.601,
    lng: 73.064,
    ownerName: 'Sajjad Hussain',
    ownerContact: '03451234502',
    menu: [
      {
        name: 'Nihari & Haleem',
        items: [
          p('Beef Nihari (Single)', 'Overnight-simmered nihari with bone marrow.', 480, IMG.nihari, { isPopular: true }),
          p('Maghaz Nihari', 'Nihari with brain masala.', 620, IMG.nihari),
          p('Beef Haleem', 'Slow-cooked wheat and lentil haleem.', 420, IMG.haleem, { isPopular: true }),
          p('Paya (Single)', 'Trotters in a rich gravy.', 520, IMG.curry),
        ],
      },
      {
        name: 'Breakfast',
        items: [
          p('Halwa Puri (Full)', 'Two puris, halwa, channa and aloo.', 380, IMG.halwa, { isVeg: true, isPopular: true }),
          p('Channa Chaat', 'Spiced chickpeas with chutney.', 220, IMG.chaat, { isVeg: true }),
          p('Anda Paratha', 'Fried egg folded into a paratha.', 260, IMG.paratha, { isVeg: true }),
        ],
      },
      {
        name: 'Breads',
        items: [
          p('Khameeri Roti', 'Traditional leavened roti for nihari.', 60, IMG.roti, { isVeg: true }),
          p('Tandoori Roti', 'Fresh off the tandoor.', 30, IMG.roti, { isVeg: true }),
          p('Paratha', 'Flaky and crisp.', 100, IMG.paratha, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Doodh Patti Chai', 'Strong milk tea.', 120, IMG.chai, { isVeg: true }),
          p('Salted Lassi', 'Cooling and savoury.', 160, IMG.lassi, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'rwp-saddar-super-store',
    name: 'Saddar Super Store',
    city: 'Rawalpindi',
    category: 'GROCERY',
    photo: 'photo-1601599561213-832382fd07ba',
    rating: 4.5,
    ratingCount: 1460,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 79,
    minOrder: 700,
    distanceKm: 3.0,
    tags: ['Grocery', 'Daily Needs'],
    isOpen: true,
    area: 'Saddar',
    address: 'Kashmir Road, Saddar, Rawalpindi',
    lat: 33.594,
    lng: 73.051,
    ownerName: 'Rashid Mahmood',
    ownerContact: '03451234503',
    menu: groceryMenu(0),
  },
  {
    slug: 'rwp-murree-road-chemist',
    name: 'Murree Road Chemist',
    city: 'Rawalpindi',
    category: 'PHARMACY',
    photo: 'photo-1576602976047-174e57a47881',
    rating: 4.7,
    ratingCount: 980,
    deliveryTimeMin: 20,
    deliveryTimeMax: 35,
    deliveryFee: 69,
    minOrder: 250,
    distanceKm: 2.1,
    tags: ['Pharmacy', 'Medicine', '24/7'],
    isOpen: true,
    area: 'Murree Road',
    address: 'Near Liaquat Bagh, Murree Road, Rawalpindi',
    lat: 33.602,
    lng: 73.067,
    ownerName: 'Dr. Faisal Iqbal',
    ownerContact: '03451234504',
    menu: pharmacyMenu(),
  },

  // ───────────────────────── Peshawar ─────────────────────────
  {
    slug: 'psh-namak-mandi-tikka',
    name: 'Namak Mandi Tikka House',
    city: 'Peshawar',
    category: 'RESTAURANTS',
    photo: 'photo-1544025162-d76694265947',
    rating: 4.9,
    ratingCount: 7210,
    deliveryTimeMin: 30,
    deliveryTimeMax: 45,
    deliveryFee: 79,
    minOrder: 400,
    distanceKm: 2.6,
    tags: ['Tikka', 'Namak Mandi', 'Mutton'],
    isOpen: true,
    promoLabel: "Peshawar's most ordered tikka",
    area: 'Namak Mandi',
    address: 'Namak Mandi Food Street, Peshawar',
    lat: 34.0075,
    lng: 71.568,
    ownerName: 'Noor Wali Khan',
    ownerContact: '03411234501',
    menu: [
      {
        name: 'Namak Mandi Tikka',
        items: [
          p('Mutton Tikka (1 kg)', 'Salt-only marinated mutton, grilled in its own fat. The Namak Mandi original.', 3200, IMG.chops, { isPopular: true, unit: '1 kg' }),
          p('Mutton Tikka (Half kg)', 'Half portion of the signature tikka.', 1650, IMG.chops, { unit: '500 g' }),
          p('Mutton Karahi (1 kg)', 'Peshawari karahi — tomato, salt, mutton, nothing else.', 3400, IMG.karahi, { isPopular: true, unit: '1 kg' }),
          p('Chicken Karahi (Full)', 'Peshawari-style white karahi.', 1850, IMG.karahi),
          p('Lamb Chops (4 pcs)', 'Charcoal-grilled chops.', 1550, IMG.chops),
        ],
      },
      {
        name: 'Chapli Kabab',
        items: [
          p('Beef Chapli Kabab (2 pcs)', 'Peshawar-style flat kabab with tomato and pomegranate seed.', 560, IMG.seekh, { isPopular: true }),
          p('Chicken Chapli Kabab (2 pcs)', 'A lighter chicken version.', 480, IMG.seekh),
          p('Seekh Kabab (4 pcs)', 'Minced beef seekh.', 520, IMG.seekh),
        ],
      },
      {
        name: 'Rice & Bread',
        items: [
          p('Kabuli Pulao', 'Carrot, raisin and lamb pulao.', 680, IMG.pulao, { isPopular: true }),
          p('Peshawari Naan', 'Large sesame-topped tandoor naan.', 100, IMG.naan, { isVeg: true }),
          p('Tandoori Roti', 'Fresh tandoor roti.', 30, IMG.roti, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Green Kahwa', 'Cardamom green tea — the traditional finish.', 140, IMG.kahwa, { isVeg: true, isPopular: true }),
          p('Doodh Patti Chai', 'Strong milk tea.', 130, IMG.chai, { isVeg: true }),
          p('Soft Drink 1.5L', 'Coke, Sprite or Fanta.', 200, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'psh-qissa-khwani-chai',
    name: 'Qissa Khwani Chai House',
    city: 'Peshawar',
    category: 'RESTAURANTS',
    photo: 'photo-1571934811356-5cc061b6821f',
    rating: 4.6,
    ratingCount: 2410,
    deliveryTimeMin: 20,
    deliveryTimeMax: 35,
    deliveryFee: 69,
    minOrder: 250,
    distanceKm: 1.9,
    tags: ['Chai', 'Breakfast', 'Cafe'],
    isOpen: true,
    area: 'Qissa Khwani Bazaar',
    address: 'Qissa Khwani Bazaar, Peshawar',
    lat: 34.01,
    lng: 71.572,
    ownerName: 'Shahid Khan',
    ownerContact: '03411234502',
    menu: [
      {
        name: 'Chai & Kahwa',
        items: [
          p('Doodh Patti Chai', 'Boiled-down strong milk tea.', 120, IMG.chai, { isVeg: true, isPopular: true }),
          p('Green Kahwa', 'Cardamom and saffron green tea.', 130, IMG.kahwa, { isVeg: true, isPopular: true }),
          p('Kashmiri Chai', 'Pink tea with pistachio.', 220, IMG.chai, { isVeg: true }),
          p('Black Tea', 'Plain strong tea.', 90, IMG.tea, { isVeg: true }),
        ],
      },
      {
        name: 'Breakfast',
        items: [
          p('Halwa Puri', 'Puri, halwa and channa.', 340, IMG.halwa, { isVeg: true, isPopular: true }),
          p('Anda Paratha', 'Egg-stuffed paratha.', 240, IMG.paratha, { isVeg: true }),
          p('Channa Chaat', 'Spiced chickpeas.', 200, IMG.chaat, { isVeg: true }),
          p('Omelette & Paratha', 'Masala omelette with a flaky paratha.', 280, IMG.paratha, { isVeg: true }),
        ],
      },
      {
        name: 'Snacks',
        items: [
          p('Samosa (4 pcs)', 'Crisp potato samosas with chutney.', 160, IMG.samosa, { isVeg: true }),
          p('Pakora Plate', 'Mixed vegetable pakoras.', 180, IMG.samosa, { isVeg: true }),
          p('Cake Rusk', 'Twice-baked, for dunking in chai.', 150, IMG.biscuits, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'psh-university-road-mart',
    name: 'University Road Mart',
    city: 'Peshawar',
    category: 'GROCERY',
    photo: 'photo-1601599561213-832382fd07ba',
    rating: 4.5,
    ratingCount: 1180,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 79,
    minOrder: 700,
    distanceKm: 3.2,
    tags: ['Grocery', 'Daily Needs'],
    isOpen: true,
    area: 'University Road',
    address: 'University Road, Peshawar',
    lat: 34.004,
    lng: 71.51,
    ownerName: 'Zubair Shah',
    ownerContact: '03411234503',
    menu: groceryMenu(-0.03),
  },
  {
    slug: 'psh-sarhad-medical-store',
    name: 'Sarhad Medical Store',
    city: 'Peshawar',
    category: 'PHARMACY',
    photo: 'photo-1576602976047-174e57a47881',
    rating: 4.7,
    ratingCount: 860,
    deliveryTimeMin: 20,
    deliveryTimeMax: 35,
    deliveryFee: 69,
    minOrder: 250,
    distanceKm: 2.4,
    tags: ['Pharmacy', 'Medicine'],
    isOpen: true,
    area: 'Saddar',
    address: 'Saddar Road, Peshawar Cantt',
    lat: 33.998,
    lng: 71.54,
    ownerName: 'Dr. Imran Yousafzai',
    ownerContact: '03411234504',
    menu: pharmacyMenu(),
  },

  // ───────────────────────── Quetta ─────────────────────────
  {
    slug: 'qta-lehri-sajji-house',
    name: 'Lehri Sajji House',
    city: 'Quetta',
    category: 'RESTAURANTS',
    photo: 'photo-1626645738196-c2a7c87a8f58',
    rating: 4.8,
    ratingCount: 3480,
    deliveryTimeMin: 35,
    deliveryTimeMax: 50,
    deliveryFee: 89,
    minOrder: 400,
    distanceKm: 2.4,
    tags: ['Sajji', 'Balochi', 'BBQ'],
    isOpen: true,
    promoLabel: 'Whole sajji with kaak — Quetta special',
    area: 'Jinnah Road',
    address: 'Jinnah Road, Quetta',
    lat: 30.189,
    lng: 66.995,
    ownerName: 'Abdul Rauf Baloch',
    ownerContact: '03811234501',
    menu: [
      {
        name: 'Sajji',
        items: [
          p('Chicken Sajji (Whole)', 'Whole chicken, salt-cured and slow-roasted on a skewer, served with rice stuffing.', 1850, IMG.friedChicken, { isPopular: true }),
          p('Chicken Sajji (Half)', 'Half sajji with rice.', 980, IMG.friedChicken),
          p('Mutton Sajji (Leg)', 'Balochi-style roasted mutton leg.', 3800, IMG.chops, { isPopular: true }),
          p('Sajji Rice (Plate)', 'The spiced rice served under the sajji.', 280, IMG.rice),
        ],
      },
      {
        name: 'Rosh & Karahi',
        items: [
          p('Balochi Rosh (Half kg)', 'Mutton slow-cooked in its own fat with salt only.', 1750, IMG.curry, { isPopular: true, unit: '500 g' }),
          p('Mutton Karahi (Half)', 'Quetta-style tomato karahi.', 1850, IMG.karahi),
          p('Chicken Karahi (Full)', 'Full chicken karahi with green chilli.', 1650, IMG.karahi),
          p('Landhi Karahi', 'Winter speciality made with cured dried meat.', 2200, IMG.curry),
        ],
      },
      {
        name: 'Bread & Sides',
        items: [
          p('Kaak', 'Stone-baked Balochi bread, the traditional sajji partner.', 150, IMG.naan, { isVeg: true, isPopular: true }),
          p('Tandoori Roti', 'Fresh tandoor roti.', 35, IMG.roti, { isVeg: true }),
          p('Salad', 'Onion, tomato, cucumber.', 90, IMG.spinach, { isVeg: true }),
          p('Green Chutney', 'Mint and coriander.', 60, IMG.spinach, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Green Kahwa', 'Quetta kahwa with cardamom.', 140, IMG.kahwa, { isVeg: true, isPopular: true }),
          p('Sabz Chai', 'Traditional Balochi green tea.', 120, IMG.tea, { isVeg: true }),
          p('Soft Drink 1.5L', 'Coke, Sprite or Fanta.', 210, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'qta-kandahari-chapli-kabab',
    name: 'Kandahari Chapli Kabab',
    city: 'Quetta',
    category: 'RESTAURANTS',
    photo: 'photo-1529042410759-befb1204b468',
    rating: 4.6,
    ratingCount: 1920,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 79,
    minOrder: 300,
    distanceKm: 2.0,
    tags: ['Chapli Kabab', 'BBQ', 'Afghan'],
    isOpen: true,
    area: 'Prince Road',
    address: 'Prince Road, Quetta',
    lat: 30.183,
    lng: 66.989,
    ownerName: 'Haji Nasrullah',
    ownerContact: '03811234502',
    menu: [
      {
        name: 'Kabab',
        items: [
          p('Beef Chapli Kabab (2 pcs)', 'Large flat kababs with tomato and coriander.', 520, IMG.seekh, { isPopular: true }),
          p('Chicken Chapli Kabab (2 pcs)', 'A lighter chicken version.', 460, IMG.seekh),
          p('Beef Seekh Kabab (4 pcs)', 'Charcoal-grilled minced beef.', 540, IMG.seekh),
          p('Shinwari Tikka', 'Salt-marinated mutton tikka.', 1450, IMG.chops),
        ],
      },
      {
        name: 'Rice',
        items: [
          p('Kabuli Pulao', 'Carrot, raisin and lamb.', 720, IMG.pulao, { isPopular: true }),
          p('Plain Rice', 'Steamed basmati.', 220, IMG.rice, { isVeg: true }),
        ],
      },
      {
        name: 'Bread & Drinks',
        items: [
          p('Afghani Naan', 'Long sesame naan.', 110, IMG.naan, { isVeg: true }),
          p('Tandoori Roti', 'Fresh tandoor roti.', 35, IMG.roti, { isVeg: true }),
          p('Green Kahwa', 'Cardamom green tea.', 130, IMG.kahwa, { isVeg: true }),
          p('Doogh', 'Salted yogurt drink with mint.', 180, IMG.lassi, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'qta-quetta-karyana-mart',
    name: 'Quetta Karyana Mart',
    city: 'Quetta',
    category: 'GROCERY',
    photo: 'photo-1601599561213-832382fd07ba',
    rating: 4.4,
    ratingCount: 740,
    deliveryTimeMin: 30,
    deliveryTimeMax: 45,
    deliveryFee: 89,
    minOrder: 700,
    distanceKm: 2.9,
    tags: ['Grocery', 'Daily Needs', 'Dry Fruit'],
    isOpen: true,
    area: 'Jinnah Road',
    address: 'Liaquat Bazaar, Jinnah Road, Quetta',
    lat: 30.186,
    lng: 66.993,
    ownerName: 'Bashir Ahmed',
    ownerContact: '03811234503',
    menu: [
      ...groceryMenu(0.06),
      {
        name: 'Quetta Dry Fruit',
        items: [
          p('Almonds (500g)', 'Balochistan almonds, freshly shelled.', 2400, IMG.apple, { isVeg: true, unit: '500 g', isPopular: true }),
          p('Pistachios (500g)', 'Roasted and salted.', 3200, IMG.apple, { isVeg: true, unit: '500 g' }),
          p('Dried Apricots (500g)', 'Sun-dried Balochi apricots.', 1100, IMG.apple, { isVeg: true, unit: '500 g' }),
          p('Walnuts (500g)', 'In-shell walnuts.', 1650, IMG.apple, { isVeg: true, unit: '500 g' }),
        ],
      },
    ],
  },
  {
    slug: 'qta-bolan-pharmacy',
    name: 'Bolan Pharmacy',
    city: 'Quetta',
    category: 'PHARMACY',
    photo: 'photo-1576602976047-174e57a47881',
    rating: 4.6,
    ratingCount: 620,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 79,
    minOrder: 250,
    distanceKm: 2.2,
    tags: ['Pharmacy', 'Medicine'],
    isOpen: true,
    area: 'Jinnah Road',
    address: 'Near Civil Hospital, Jinnah Road, Quetta',
    lat: 30.192,
    lng: 66.998,
    ownerName: 'Dr. Samina Kakar',
    ownerContact: '03811234504',
    menu: pharmacyMenu(),
  },
];
