/**
 * Seed catalog for the Lahore market. Mirrors the data the mobile app used to
 * hard-code, so the app looks identical once it is pointed at the real API.
 */

const img = (id: string, w = 800) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=75`;

export const IMG = {
  karahi: img('photo-1631452180519-c014fe946bc7', 400),
  curry: img('photo-1585937421612-70a008356fbe', 400),
  handi: img('photo-1603894584373-5ac82b2ae398', 400),
  biryani: img('photo-1563379091339-03b21ab4a4f8', 400),
  biryani2: img('photo-1589302168068-964664d93dc0', 400),
  pulao: img('photo-1596797038530-2c107229654b', 400),
  rice: img('photo-1586201375761-83865001e31c', 400),
  seekh: img('photo-1599487488170-d11ec9c172f0', 400),
  tikka: img('photo-1529042410759-befb1204b468', 400),
  bbq: img('photo-1555939594-58d7cb561ad1', 400),
  chops: img('photo-1544025162-d76694265947', 400),
  naan: img('photo-1601050690597-df0568f70950', 400),
  roti: img('photo-1626074353765-517a681e40be', 400),
  paratha: img('photo-1567337710282-00832b415979', 400),
  samosa: img('photo-1601050690117-94f5f6fa8bd7', 400),
  chaat: img('photo-1606491956689-2ea866880c84', 400),
  chai: img('photo-1571934811356-5cc061b6821f', 400),
  tea: img('photo-1544787219-7f47ccb76574', 400),
  kahwa: img('photo-1564890369478-c89ca6d9cde9', 400),
  coffee: img('photo-1509042239860-f550ce710b93', 400),
  lassi: img('photo-1553530666-ba11a7da3888', 400),
  juice: img('photo-1600271886742-f049cd451bba', 400),
  lemonade: img('photo-1523677011781-c91d1bbe2f9e', 400),
  soda: img('photo-1554866585-cd94860890b7', 400),
  shake: img('photo-1572490122747-3968b75cc699', 400),
  burger: img('photo-1568901346375-23c9450c58cd', 400),
  zinger: img('photo-1606755962773-d324e0a13086', 400),
  burger2: img('photo-1594212699903-ec8a3eca50f5', 400),
  fries: img('photo-1573080496219-bb080dd4f877', 400),
  nuggets: img('photo-1562967914-608f82629710', 400),
  friedChicken: img('photo-1626645738196-c2a7c87a8f58', 400),
  wings: img('photo-1527477396000-e27163b481c2', 400),
  pizza: img('photo-1513104890138-7c749659a591', 400),
  pizza2: img('photo-1574071318508-1cdbab80d002', 400),
  pizza3: img('photo-1628840042765-356cda07504e', 400),
  pizza4: img('photo-1565299624946-b28f40a0ae38', 400),
  garlicBread: img('photo-1573140401552-3fab0b24306f', 400),
  pasta: img('photo-1621996346565-e3dbc646d9a9', 400),
  shawarma: img('photo-1529006557810-274b9b2fc783', 400),
  wrap: img('photo-1561651823-34feb02250e4', 400),
  roll: img('photo-1626700051175-6818013e1d4f', 400),
  hummus: img('photo-1577805947697-89e18249d767', 400),
  falafel: img('photo-1593001874117-c99c800e3eb7', 400),
  nihari: img('photo-1574484284002-952d92456975', 400),
  haleem: img('photo-1547592180-85f173990554', 400),
  daal: img('photo-1546833999-b9f581a1996d', 400),
  halwa: img('photo-1587314168485-3236d6710814', 400),
  gulabJamun: img('photo-1601303516534-bf0b1eb70df4', 400),
  mithai: img('photo-1551024506-0bccd828d307', 400),
  kheer: img('photo-1488477181946-6428a0291777', 400),
  iceCream: img('photo-1563805042-7684c019e1cb', 400),
  kulfi: img('photo-1505394033641-40c6b8e6a5f7', 400),
  cake: img('photo-1578985545062-69928b1d9587', 400),
  cake2: img('photo-1571877227200-a0d98ea607e9', 400),
  cheesecake: img('photo-1524351199678-941a58a3df50', 400),
  noodles: img('photo-1585032226651-759b368d7246', 400),
  chinese: img('photo-1525755662778-989d0524087e', 400),
  soup: img('photo-1547592166-23ac45744acd', 400),
  prawns: img('photo-1559847844-5315695dadae', 400),
  springRoll: img('photo-1496116218417-1a781b1c416c', 400),
  atta: img('photo-1574323347407-f5e1ad6d020b', 400),
  oil: img('photo-1474979266404-7eaacbcd87c5', 400),
  sugar: img('photo-1581268497089-9da1a3a3a8d1', 400),
  lentils: img('photo-1515543904379-3d757afe72e4', 400),
  milk: img('photo-1550583724-b2692b85b150', 400),
  eggs: img('photo-1582722872445-44dc5f7e3c8f', 400),
  yogurt: img('photo-1488477181946-6428a0291777', 400),
  butter: img('photo-1589985270826-4b7bb135bc9d', 400),
  cheese: img('photo-1486297678162-eb2a19b0a32d', 400),
  biscuits: img('photo-1558961363-fa8fdf82db35', 400),
  chips: img('photo-1566478989037-eec170784d0b', 400),
  detergent: img('photo-1610557892470-55d9e80c0bce', 400),
  tissues: img('photo-1584308666744-24d5c474f2ae', 400),
  potatoes: img('photo-1518977676601-b53f82aba655', 400),
  onions: img('photo-1508747703725-719777637510', 400),
  tomatoes: img('photo-1592924357228-91a4daadcfea', 400),
  chillies: img('photo-1583119912267-cc97c911e416', 400),
  ginger: img('photo-1615485500704-8e990f9900f7', 400),
  spinach: img('photo-1576045057995-568f588f82fb', 400),
  okra: img('photo-1425543103986-22abb7d7e8d2', 400),
  cauliflower: img('photo-1568584711075-3d021a7c3ca3', 400),
  lemon: img('photo-1590502593747-42a996133562', 400),
  mango: img('photo-1553279768-865429fa0078', 400),
  banana: img('photo-1571771894821-ce9b6c11b08e', 400),
  apple: img('photo-1560806887-1e4cd0b6cbd6', 400),
  grapes: img('photo-1537640538966-79f369143f8f', 400),
  guava: img('photo-1536511132770-e5058c7e8c46', 400),
  pomegranate: img('photo-1541344999736-83eca272f6fc', 400),
  orange: img('photo-1547514701-42782101795e', 400),
  watermelon: img('photo-1587049352846-4a222e784d38', 400),
  bread: img('photo-1509440159596-0249088772ff', 400),
  buns: img('photo-1549931319-a545dcf3bc73', 400),
  rusk: img('photo-1555507036-ab1f4038808a', 400),
  patties: img('photo-1509365465985-25d11c17e812', 400),
  brownie: img('photo-1607920591413-4ec007e70023', 400),
  cookies: img('photo-1499636136210-6f4ee915583e', 400),
  tablets: img('photo-1584308666744-24d5c474f2ae', 400),
  medicine: img('photo-1471864190281-a93a3070b6de', 400),
  syrup: img('photo-1587854692152-cbe660dbde88', 400),
  vitamins: img('photo-1550572017-edd951b55104', 400),
  omega: img('photo-1577401239170-897942555fb3', 400),
  sanitizer: img('photo-1584744982491-665216d95f8b', 400),
  toothpaste: img('photo-1559591937-abc3a5d51f42', 400),
  mask: img('photo-1586942593568-29361efcd571', 400),
  sunscreen: img('photo-1556228720-195a672e8a03', 400),
  diapers: img('photo-1515488042361-ee00e0ddd4e4', 400),
  wipes: img('photo-1519689680058-324335c77eba', 400),
  lotion: img('photo-1556228578-8c89e6adf883', 400),
  thermometer: img('photo-1584036561566-baf8f5f1b144', 400),
  bpMonitor: img('photo-1615486511484-92e172cc4fe0', 400),
  glucometer: img('photo-1579684385127-1ef15d508118', 400),
  nebulizer: img('photo-1584982751601-97dcc096659c', 400),
  whey: img('photo-1593095948071-474c5cc2989d', 400),
  electrolyte: img('photo-1622484212850-eb596d769edc', 400),
  bandage: img('photo-1603398938378-e54eab446dde', 400),
  spray: img('photo-1631549916768-4119b2e5f926', 400),
  feeder: img('photo-1519689680058-324335c77eba', 400),
};

export type SeedProduct = {
  name: string;
  description: string;
  price: number;
  image: string;
  unit?: string;
  isVeg?: boolean;
  isPopular?: boolean;
  compareAtPrice?: number;
};

export type SeedStore = {
  slug: string;
  name: string;
  category: 'RESTAURANTS' | 'GROCERY' | 'PHARMACY';
  photo: string;
  rating: number;
  ratingCount: number;
  deliveryTimeMin: number;
  deliveryTimeMax: number;
  deliveryFee: number;
  minOrder: number;
  distanceKm: number;
  tags: string[];
  isOpen: boolean;
  promoLabel?: string;
  area: string;
  address: string;
  lat: number;
  lng: number;
  ownerName: string;
  ownerContact: string;
  menu: Array<{ name: string; items: SeedProduct[] }>;
};

const p = (name: string, description: string, price: number, image: string, extra: Partial<SeedProduct> = {}): SeedProduct => ({ name, description, price, image, ...extra });

export const STORES: SeedStore[] = [
  {
    slug: 'karahi-point',
    name: 'Karahi Point',
    category: 'RESTAURANTS',
    photo: 'photo-1631452180519-c014fe946bc7',
    rating: 4.7,
    ratingCount: 3120,
    deliveryTimeMin: 30,
    deliveryTimeMax: 40,
    deliveryFee: 99,
    minOrder: 500,
    distanceKm: 2.1,
    tags: ['Karahi', 'Desi', 'BBQ'],
    isOpen: true,
    promoLabel: 'Free naan on orders over Rs 1,500',
    area: 'DHA Phase 5',
    address: 'Sector C, Commercial Area, DHA Phase 5, Lahore',
    lat: 31.4697,
    lng: 74.41,
    ownerName: 'Imran Sheikh',
    ownerContact: '03001234501',
    menu: [
      {
        name: 'Starters',
        items: [
          p('Seekh Kebab (4 pcs)', 'Juicy beef seekh kebabs grilled over charcoal, served with mint chutney.', 550, IMG.seekh, { isPopular: true }),
          p('Chicken Tikka (2 pcs)', 'Marinated chicken tikka, smoky and tender.', 480, IMG.tikka),
          p('Lahori Fried Fish', 'Crispy spiced river fish, a Lahore winter favourite.', 750, IMG.friedChicken),
          p('Chicken Malai Boti', 'Creamy, mild boneless boti with a hint of black pepper.', 690, IMG.bbq, { isPopular: true }),
        ],
      },
      {
        name: 'Karahi & Handi',
        items: [
          p('Chicken Karahi (Full)', 'Signature desi chicken karahi with fresh tomatoes, ginger and green chillies. Serves 3-4.', 1850, IMG.karahi, { isPopular: true }),
          p('Chicken Karahi (Half)', 'Our signature karahi in a half portion. Serves 1-2.', 990, IMG.karahi),
          p('Mutton Karahi (Half)', 'Slow-cooked mutton karahi with bone-in pieces.', 1650, IMG.curry),
          p('White Chicken Karahi', 'Creamy cashew and yogurt based karahi.', 1150, IMG.handi),
          p('Chicken Boneless Handi', 'Rich, buttery boneless chicken handi.', 1250, IMG.handi, { isPopular: true }),
          p('Daal Makhani', 'Overnight simmered black lentils with butter and cream.', 450, IMG.daal, { isVeg: true }),
        ],
      },
      {
        name: 'Breads & Rice',
        items: [
          p('Tandoori Roti', 'Fresh from the tandoor.', 30, IMG.roti, { isVeg: true }),
          p('Garlic Naan', 'Soft naan brushed with garlic butter.', 80, IMG.naan, { isVeg: true, isPopular: true }),
          p('Roghni Naan', 'Sesame-topped, slightly sweet naan.', 70, IMG.naan, { isVeg: true }),
          p('Plain Basmati Rice', 'Steamed long-grain basmati.', 250, IMG.rice, { isVeg: true }),
          p('Kabuli Pulao', 'Afghan-style pulao with carrots, raisins and tender beef.', 550, IMG.pulao),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Mint Margarita', 'Fresh mint, lemon and soda.', 250, IMG.lemonade, { isVeg: true, isPopular: true }),
          p('Sweet Lassi', 'Thick Punjabi lassi topped with malai.', 180, IMG.lassi, { isVeg: true }),
          p('Soft Drink 1.5L', 'Coke, Sprite or Fanta.', 200, IMG.soda, { isVeg: true }),
          p('Fresh Lime Soda', 'Sweet or salted.', 150, IMG.lemonade, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'biryani-express',
    name: 'Biryani Express',
    category: 'RESTAURANTS',
    photo: 'photo-1563379091339-03b21ab4a4f8',
    rating: 4.6,
    ratingCount: 5480,
    deliveryTimeMin: 25,
    deliveryTimeMax: 35,
    deliveryFee: 0,
    minOrder: 400,
    distanceKm: 1.4,
    tags: ['Biryani', 'Pulao', 'Desi'],
    isOpen: true,
    promoLabel: 'Free delivery',
    area: 'Gulberg III',
    address: 'Main Boulevard, Gulberg III, Lahore',
    lat: 31.51,
    lng: 74.348,
    ownerName: 'Adnan Malik',
    ownerContact: '03001234502',
    menu: [
      {
        name: 'Biryani & Rice',
        items: [
          p('Chicken Biryani', 'Classic Lahori chicken biryani with aloo, served with raita.', 350, IMG.biryani, { isPopular: true }),
          p('Beef Biryani', 'Tender beef chunks layered with fragrant basmati.', 420, IMG.biryani2),
          p('Mutton Biryani', 'Premium mutton biryani, dum-cooked.', 650, IMG.biryani2, { isPopular: true }),
          p('Sindhi Biryani', 'Spicy Sindhi style with potatoes and tomatoes.', 380, IMG.biryani),
          p('Chicken Yakhni Pulao', 'Mild, aromatic pulao cooked in chicken stock.', 320, IMG.pulao),
          p('Prawn Biryani', 'Karachi-style prawn biryani.', 750, IMG.prawns),
          p('Family Deal (Serves 4)', '4 chicken biryani, 4 raita, 1.5L drink.', 1450, IMG.biryani, { compareAtPrice: 1650, isPopular: true }),
        ],
      },
      {
        name: 'Sides',
        items: [
          p('Mint Raita', 'Cooling yogurt with mint and cumin.', 60, IMG.yogurt, { isVeg: true }),
          p('Shami Kebab (2 pcs)', 'Beef and chana daal kebabs, shallow fried.', 120, IMG.seekh),
          p('Fresh Salad', 'Onion, cucumber, tomato and lemon.', 80, IMG.chaat, { isVeg: true }),
          p('Chicken Boti (6 pcs)', 'Charcoal grilled boneless boti.', 350, IMG.tikka),
        ],
      },
      {
        name: 'Desserts',
        items: [
          p('Kheer', 'Slow-cooked rice pudding with cardamom and pistachio.', 150, IMG.kheer, { isVeg: true, isPopular: true }),
          p('Gulab Jamun (2 pcs)', 'Soft, syrupy and warm.', 120, IMG.gulabJamun, { isVeg: true }),
          p('Zarda', 'Sweet saffron rice with dry fruits.', 150, IMG.rice, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Soft Drink 1.5L', 'Chilled Coke, Sprite or Fanta.', 200, IMG.soda, { isVeg: true }),
          p('Sweet Lassi', 'Traditional Punjabi lassi.', 150, IMG.lassi, { isVeg: true }),
          p('Soft Drink (Can)', '250ml can.', 100, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'tikka-tarang',
    name: 'Tikka Tarang BBQ',
    category: 'RESTAURANTS',
    photo: 'photo-1599487488170-d11ec9c172f0',
    rating: 4.8,
    ratingCount: 2210,
    deliveryTimeMin: 35,
    deliveryTimeMax: 45,
    deliveryFee: 129,
    minOrder: 600,
    distanceKm: 2.6,
    tags: ['BBQ', 'Tikka', 'Kebabs'],
    isOpen: true,
    area: 'MM Alam Road',
    address: 'MM Alam Road, Gulberg III, Lahore',
    lat: 31.509,
    lng: 74.352,
    ownerName: 'Tariq Javed',
    ownerContact: '03001234503',
    menu: [
      {
        name: 'BBQ',
        items: [
          p('Chicken Tikka (Leg)', 'Classic Lahori tikka, charred and spicy.', 450, IMG.tikka, { isPopular: true }),
          p('Chicken Malai Boti', 'Creamy marinated boneless boti.', 690, IMG.bbq, { isPopular: true }),
          p('Reshmi Kebab', 'Silky minced chicken kebabs.', 620, IMG.seekh),
          p('Beef Seekh Kebab (4 pcs)', 'Spiced minced beef on skewers.', 550, IMG.seekh),
          p('Mutton Chops (4 pcs)', 'Marinated mutton chops grilled to perfection.', 1450, IMG.chops),
          p('Beef Bihari Boti', 'Tender Bihari-style beef boti with mustard oil marinade.', 720, IMG.bbq),
          p('BBQ Platter (Serves 2)', 'Tikka, malai boti, seekh kebab, naan and raita.', 2450, IMG.bbq, { compareAtPrice: 2750, isPopular: true }),
        ],
      },
      {
        name: 'Naan & Rice',
        items: [
          p('Roghni Naan', 'Sesame topped naan.', 70, IMG.naan, { isVeg: true }),
          p('Kulcha', 'Soft tandoori kulcha.', 60, IMG.roti, { isVeg: true }),
          p('Namkeen Rice', 'Lightly spiced rice, perfect with BBQ.', 300, IMG.rice, { isVeg: true }),
        ],
      },
      {
        name: 'Sides & Chutneys',
        items: [
          p('Mint Raita', 'House raita.', 70, IMG.yogurt, { isVeg: true }),
          p('Kachumber Salad', 'Chopped onion, tomato, cucumber and lemon.', 100, IMG.chaat, { isVeg: true }),
          p('Imli Chutney', 'Tangy tamarind chutney.', 50, IMG.chaat, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Peshawari Kahwa', 'Green tea with cardamom.', 180, IMG.kahwa, { isVeg: true }),
          p('Doodh Patti', 'Strong milk tea.', 150, IMG.chai, { isVeg: true }),
          p('Soft Drink 1.5L', 'Chilled.', 200, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'burger-junction',
    name: 'Burger Junction',
    category: 'RESTAURANTS',
    photo: 'photo-1568901346375-23c9450c58cd',
    rating: 4.5,
    ratingCount: 4120,
    deliveryTimeMin: 20,
    deliveryTimeMax: 30,
    deliveryFee: 79,
    minOrder: 350,
    distanceKm: 3.2,
    tags: ['Burgers', 'Fast Food', 'Zinger'],
    isOpen: true,
    promoLabel: 'Buy 1 Get 1 on Zinger',
    area: 'Johar Town',
    address: 'Block G1, Johar Town, Lahore',
    lat: 31.47,
    lng: 74.27,
    ownerName: 'Bilal Ahmed',
    ownerContact: '03001234504',
    menu: [
      {
        name: 'Burgers',
        items: [
          p('Zinger Burger', 'Crispy spicy chicken fillet, lettuce and mayo.', 450, IMG.zinger, { isPopular: true }),
          p('Double Decker Zinger', 'Two zinger fillets, double cheese.', 690, IMG.zinger),
          p('Classic Beef Burger', 'Grilled beef patty with cheese, onions and pickles.', 550, IMG.burger, { isPopular: true }),
          p('Smash Burger', 'Double smashed beef patties with secret sauce.', 620, IMG.burger2),
          p('Grilled Chicken Burger', 'Healthier grilled chicken with honey mustard.', 490, IMG.burger),
          p('Spicy Crunch Burger', 'Extra crunchy, extra spicy.', 470, IMG.zinger),
        ],
      },
      {
        name: 'Sides',
        items: [
          p('French Fries', 'Golden, salted fries.', 220, IMG.fries, { isVeg: true, isPopular: true }),
          p('Loaded Fries', 'Fries with cheese sauce, chicken and jalapeños.', 380, IMG.fries),
          p('Chicken Nuggets (6 pcs)', 'Crispy nuggets with dip.', 350, IMG.nuggets),
          p('Hot Wings (6 pcs)', 'Spicy fried wings.', 420, IMG.wings),
          p('Coleslaw', 'Creamy cabbage slaw.', 90, IMG.chaat, { isVeg: true }),
        ],
      },
      {
        name: 'Deals',
        items: [
          p('Zinger Meal', 'Zinger burger, fries and a drink.', 690, IMG.zinger, { compareAtPrice: 790, isPopular: true }),
          p('Family Bucket', '8 pcs fried chicken, 2 large fries, 1.5L drink.', 2200, IMG.friedChicken, { compareAtPrice: 2500 }),
          p('Kids Meal', 'Mini burger, small fries, juice.', 450, IMG.burger),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Soft Drink (Regular)', '345ml.', 100, IMG.soda, { isVeg: true }),
          p('Oreo Milkshake', 'Thick and creamy.', 350, IMG.shake, { isVeg: true }),
          p('Mint Margarita', 'Refreshing mint and lime.', 220, IMG.lemonade, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'pizza-pointe',
    name: 'Pizza Pointe',
    category: 'RESTAURANTS',
    photo: 'photo-1513104890138-7c749659a591',
    rating: 4.4,
    ratingCount: 1890,
    deliveryTimeMin: 30,
    deliveryTimeMax: 40,
    deliveryFee: 99,
    minOrder: 500,
    distanceKm: 2.9,
    tags: ['Pizza', 'Pasta', 'Italian'],
    isOpen: true,
    promoLabel: 'Flat 20% off',
    area: 'Model Town',
    address: 'Model Town Link Road, Lahore',
    lat: 31.482,
    lng: 74.32,
    ownerName: 'Hamza Qureshi',
    ownerContact: '03001234505',
    menu: [
      {
        name: 'Pizzas',
        items: [
          p('Chicken Tikka Pizza (Medium)', 'Desi tikka chunks, onions and capsicum.', 1150, IMG.pizza2, { isPopular: true }),
          p('Chicken Fajita (Medium)', 'Fajita chicken, jalapeños and cheese.', 1150, IMG.pizza3, { isPopular: true }),
          p('Malai Boti Pizza (Large)', 'Creamy malai boti on a cheesy base.', 1650, IMG.pizza),
          p('Cheese Lovers (Medium)', 'Triple cheese blend.', 950, IMG.pizza4, { isVeg: true }),
          p('Beef Pepperoni (Medium)', 'Beef pepperoni with mozzarella.', 1250, IMG.pizza3),
          p('Beef Bihari Pizza (Medium)', 'Bihari kebab topping with tangy sauce.', 1350, IMG.pizza2),
        ],
      },
      {
        name: 'Starters',
        items: [
          p('Garlic Bread', 'Cheesy garlic bread sticks.', 350, IMG.garlicBread, { isVeg: true }),
          p('Chicken Wings (6 pcs)', 'BBQ or hot.', 550, IMG.wings),
          p('Cheese Sticks', 'Mozzarella sticks with marinara.', 450, IMG.garlicBread, { isVeg: true }),
        ],
      },
      {
        name: 'Pasta',
        items: [
          p('Chicken Alfredo', 'Creamy alfredo with grilled chicken.', 850, IMG.pasta, { isPopular: true }),
          p('Penne Arrabbiata', 'Spicy tomato sauce.', 750, IMG.pasta, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Soft Drink 1.5L', 'Chilled.', 200, IMG.soda, { isVeg: true }),
          p('Lemonade', 'Fresh lemonade.', 180, IMG.lemonade, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'chai-khana',
    name: 'Chai Khana',
    category: 'RESTAURANTS',
    photo: 'photo-1571934811356-5cc061b6821f',
    rating: 4.7,
    ratingCount: 2760,
    deliveryTimeMin: 15,
    deliveryTimeMax: 25,
    deliveryFee: 49,
    minOrder: 250,
    distanceKm: 1.1,
    tags: ['Chai', 'Paratha', 'Breakfast'],
    isOpen: true,
    area: 'Liberty Market',
    address: 'Liberty Market, Gulberg III, Lahore',
    lat: 31.511,
    lng: 74.344,
    ownerName: 'Saad Rehman',
    ownerContact: '03001234506',
    menu: [
      {
        name: 'Chai & Coffee',
        items: [
          p('Doodh Patti', 'Strong, milky and sweet.', 150, IMG.chai, { isVeg: true, isPopular: true }),
          p('Karak Chai', 'Extra strong with cardamom.', 130, IMG.tea, { isVeg: true }),
          p('Kashmiri Pink Chai', 'Pink chai with pistachio and almonds.', 220, IMG.chai, { isVeg: true, isPopular: true }),
          p('Green Tea', 'Light and refreshing.', 100, IMG.kahwa, { isVeg: true }),
          p('Cold Coffee', 'Blended with ice cream.', 320, IMG.coffee, { isVeg: true }),
        ],
      },
      {
        name: 'Breakfast',
        items: [
          p('Aloo Paratha', 'Stuffed potato paratha with yogurt.', 220, IMG.paratha, { isVeg: true, isPopular: true }),
          p('Anda Paratha', 'Paratha with a fried egg.', 250, IMG.paratha),
          p('Halwa Puri Set', '2 puri, halwa, channay and achaar.', 350, IMG.halwa, { isVeg: true, isPopular: true }),
          p('Desi Omelette', 'With onions, tomatoes and green chillies.', 150, IMG.eggs),
          p('Channay', 'Spiced chickpeas.', 180, IMG.daal, { isVeg: true }),
        ],
      },
      {
        name: 'Snacks',
        items: [
          p('Samosa (2 pcs)', 'Crispy aloo samosas with chutney.', 80, IMG.samosa, { isVeg: true, isPopular: true }),
          p('Pakora Plate', 'Mixed vegetable pakoras.', 200, IMG.samosa, { isVeg: true }),
          p('Chicken Roll', 'Paratha roll with chicken and chutney.', 180, IMG.roll),
          p('Bun Kebab', 'Karachi-style bun kebab.', 150, IMG.burger),
          p('Dahi Bhalla', 'Lentil dumplings in yogurt with chutneys.', 200, IMG.chaat, { isVeg: true }),
        ],
      },
      {
        name: 'Sweets',
        items: [
          p('Zarda', 'Sweet saffron rice.', 150, IMG.rice, { isVeg: true }),
          p('Gajar Ka Halwa', 'Carrot halwa with khoya.', 220, IMG.halwa, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'shawarma-stop',
    name: 'Shawarma Stop',
    category: 'RESTAURANTS',
    photo: 'photo-1529006557810-274b9b2fc783',
    rating: 4.5,
    ratingCount: 1540,
    deliveryTimeMin: 20,
    deliveryTimeMax: 30,
    deliveryFee: 69,
    minOrder: 300,
    distanceKm: 1.8,
    tags: ['Shawarma', 'Arabic', 'Rolls'],
    isOpen: true,
    area: 'Cavalry Ground',
    address: 'Commercial Area, Cavalry Ground, Lahore',
    lat: 31.5,
    lng: 74.38,
    ownerName: 'Yasir Khan',
    ownerContact: '03001234507',
    menu: [
      {
        name: 'Shawarma',
        items: [
          p('Chicken Shawarma', 'Classic chicken shawarma with garlic sauce.', 250, IMG.shawarma, { isPopular: true }),
          p('Zinger Shawarma', 'Crispy zinger strips with spicy mayo.', 320, IMG.wrap, { isPopular: true }),
          p('Beef Shawarma', 'Marinated beef with tahini.', 350, IMG.shawarma),
          p('Cheese Shawarma', 'Loaded with melted cheese.', 300, IMG.wrap),
          p('Shawarma Platter', 'Chicken shawarma meat, rice, fries and garlic sauce.', 650, IMG.shawarma),
        ],
      },
      {
        name: 'Wraps & Rolls',
        items: [
          p('Chicken Cheese Roll', 'Paratha roll with cheese and chicken.', 280, IMG.roll),
          p('Mexican Wrap', 'Spicy chicken, beans and salsa.', 380, IMG.wrap),
          p('Chicken Paratha Roll', 'Classic Lahori paratha roll.', 260, IMG.roll, { isPopular: true }),
        ],
      },
      {
        name: 'Sides',
        items: [
          p('Garlic Mayo Fries', 'Fries tossed in garlic mayo.', 260, IMG.fries, { isVeg: true }),
          p('Hummus with Pita', 'Creamy hummus and warm pita.', 350, IMG.hummus, { isVeg: true }),
          p('Falafel (6 pcs)', 'Crispy chickpea falafel.', 300, IMG.falafel, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Fresh Juice', 'Orange, apple or mango.', 250, IMG.juice, { isVeg: true }),
          p('Soft Drink (Regular)', '345ml.', 100, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'desi-dastarkhwan',
    name: 'Desi Dastarkhwan',
    category: 'RESTAURANTS',
    photo: 'photo-1574484284002-952d92456975',
    rating: 4.6,
    ratingCount: 3360,
    deliveryTimeMin: 30,
    deliveryTimeMax: 45,
    deliveryFee: 89,
    minOrder: 400,
    distanceKm: 4.5,
    tags: ['Nihari', 'Haleem', 'Halwa Puri'],
    isOpen: false,
    area: 'Anarkali',
    address: 'Old Anarkali Food Street, Lahore',
    lat: 31.567,
    lng: 74.309,
    ownerName: 'Rashid Ali',
    ownerContact: '03001234508',
    menu: [
      {
        name: 'Signature Dishes',
        items: [
          p('Beef Nihari', 'Overnight slow-cooked nihari with ginger and lemon.', 550, IMG.nihari, { isPopular: true }),
          p('Mutton Nihari', 'Premium mutton nihari.', 850, IMG.nihari),
          p('Haleem', 'Wheat, lentils and beef, cooked for hours.', 380, IMG.haleem, { isPopular: true }),
          p('Siri Paye', 'Traditional Lahori paye.', 650, IMG.curry),
          p('Chicken Qorma', 'Rich, aromatic qorma.', 480, IMG.curry),
          p('Daal Mash', 'Dry white lentils with ginger.', 250, IMG.daal, { isVeg: true }),
        ],
      },
      {
        name: 'Breads',
        items: [
          p('Tandoori Roti', 'Fresh tandoori roti.', 30, IMG.roti, { isVeg: true }),
          p('Naan', 'Soft naan.', 50, IMG.naan, { isVeg: true }),
          p('Puri (2 pcs)', 'Fluffy fried puris.', 60, IMG.paratha, { isVeg: true }),
        ],
      },
      {
        name: 'Breakfast',
        items: [
          p('Halwa Puri Set', 'Puri, halwa, channay and aloo bhujia.', 320, IMG.halwa, { isVeg: true, isPopular: true }),
          p('Lassi', 'Sweet or salted.', 150, IMG.lassi, { isVeg: true }),
        ],
      },
      {
        name: 'Desserts',
        items: [
          p('Kheer', 'Rice pudding.', 150, IMG.kheer, { isVeg: true }),
          p('Suji Halwa', 'Semolina halwa.', 120, IMG.halwa, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'mithai-more',
    name: 'Mithai & More',
    category: 'RESTAURANTS',
    photo: 'photo-1551024506-0bccd828d307',
    rating: 4.8,
    ratingCount: 1980,
    deliveryTimeMin: 20,
    deliveryTimeMax: 30,
    deliveryFee: 59,
    minOrder: 300,
    distanceKm: 1.6,
    tags: ['Mithai', 'Desserts', 'Ice Cream'],
    isOpen: true,
    promoLabel: 'Eid special boxes',
    area: 'Gulberg II',
    address: 'Main Market, Gulberg II, Lahore',
    lat: 31.52,
    lng: 74.355,
    ownerName: 'Faisal Butt',
    ownerContact: '03001234509',
    menu: [
      {
        name: 'Mithai',
        items: [
          p('Gulab Jamun (500g)', 'Soft khoya gulab jamun in syrup.', 550, IMG.gulabJamun, { isVeg: true, isPopular: true }),
          p('Barfi (500g)', 'Classic milk barfi.', 700, IMG.mithai, { isVeg: true }),
          p('Rasgulla (500g)', 'Spongy and light.', 500, IMG.gulabJamun, { isVeg: true }),
          p('Jalebi (500g)', 'Crispy and syrupy.', 400, IMG.mithai, { isVeg: true, isPopular: true }),
          p('Kaju Katli (250g)', 'Premium cashew fudge.', 750, IMG.mithai, { isVeg: true }),
          p('Mixed Mithai Box (1kg)', 'Assorted premium mithai gift box.', 1400, IMG.mithai, { isVeg: true, compareAtPrice: 1600 }),
        ],
      },
      {
        name: 'Ice Cream & Kulfi',
        items: [
          p('Mango Ice Cream', 'Made with Chaunsa mangoes.', 250, IMG.iceCream, { isVeg: true, isPopular: true }),
          p('Kulfi', 'Traditional pistachio kulfi.', 150, IMG.kulfi, { isVeg: true }),
          p('Falooda', 'Kulfi, vermicelli, basil seeds and rose syrup.', 320, IMG.iceCream, { isVeg: true }),
        ],
      },
      {
        name: 'Cakes',
        items: [
          p('Chocolate Fudge Cake (1 lb)', 'Rich fudge cake.', 1200, IMG.cake, { isVeg: true, isPopular: true }),
          p('Pineapple Cake (1 lb)', 'Fresh cream pineapple cake.', 1100, IMG.cake2, { isVeg: true }),
          p('Cheesecake Slice', 'Baked New York style.', 450, IMG.cheesecake, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Mango Lassi', 'Thick mango lassi.', 220, IMG.lassi, { isVeg: true }),
          p('Rooh Afza Milk', 'Chilled rose milk.', 150, IMG.milk, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'wok-n-roll',
    name: 'Wok N Roll',
    category: 'RESTAURANTS',
    photo: 'photo-1585032226651-759b368d7246',
    rating: 4.3,
    ratingCount: 980,
    deliveryTimeMin: 35,
    deliveryTimeMax: 45,
    deliveryFee: 119,
    minOrder: 500,
    distanceKm: 6.2,
    tags: ['Chinese', 'Noodles', 'Soups'],
    isOpen: true,
    area: 'Bahria Town',
    address: 'Sector C, Bahria Town, Lahore',
    lat: 31.365,
    lng: 74.18,
    ownerName: 'Nadia Aslam',
    ownerContact: '03001234510',
    menu: [
      {
        name: 'Chinese Mains',
        items: [
          p('Chicken Manchurian', 'Sweet and tangy Manchurian with rice.', 750, IMG.chinese, { isPopular: true }),
          p('Chicken Chowmein', 'Stir-fried noodles with vegetables.', 650, IMG.noodles, { isPopular: true }),
          p('Beef Chilli Dry', 'Spicy dry beef with capsicum.', 850, IMG.chinese),
          p('Sweet & Sour Chicken', 'Crispy chicken in sweet and sour sauce.', 780, IMG.chinese),
          p('Egg Fried Rice', 'Wok-tossed with eggs and spring onion.', 450, IMG.rice),
          p('Singaporean Rice', 'Rice, noodles, chicken and creamy sauce.', 850, IMG.noodles),
        ],
      },
      {
        name: 'Soups',
        items: [
          p('Hot & Sour Soup', 'Classic spicy and tangy.', 350, IMG.soup),
          p('Chicken Corn Soup', 'Mild and comforting.', 320, IMG.soup, { isPopular: true }),
        ],
      },
      {
        name: 'Starters',
        items: [
          p('Dynamite Prawns', 'Crispy prawns in spicy mayo.', 950, IMG.prawns),
          p('Crispy Chicken', 'Honey chilli crispy chicken.', 650, IMG.friedChicken),
          p('Spring Rolls (4 pcs)', 'Vegetable spring rolls.', 300, IMG.springRoll, { isVeg: true }),
        ],
      },
      {
        name: 'Drinks',
        items: [
          p('Peach Iced Tea', 'Refreshing.', 220, IMG.tea, { isVeg: true }),
          p('Soft Drink (Regular)', '345ml.', 100, IMG.soda, { isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'fresh-basket',
    name: 'Fresh Basket Mart',
    category: 'GROCERY',
    photo: 'photo-1542838132-92c53300491e',
    rating: 4.6,
    ratingCount: 6210,
    deliveryTimeMin: 30,
    deliveryTimeMax: 45,
    deliveryFee: 149,
    minOrder: 800,
    distanceKm: 2.3,
    tags: ['Groceries', 'Staples', 'Household'],
    isOpen: true,
    promoLabel: 'Free delivery over Rs 2,000',
    area: 'DHA Phase 4',
    address: 'Commercial Area, DHA Phase 4, Lahore',
    lat: 31.475,
    lng: 74.39,
    ownerName: 'Kamran Iqbal',
    ownerContact: '03001234511',
    menu: [
      {
        name: 'Staples',
        items: [
          p('Chakki Atta', 'Fine wheat flour.', 1450, IMG.atta, { unit: '10 kg bag', isVeg: true, isPopular: true }),
          p('Super Kernel Basmati', 'Aged long-grain basmati rice.', 1650, IMG.rice, { unit: '5 kg bag', isVeg: true, isPopular: true }),
          p('Sugar', 'Refined white sugar.', 175, IMG.sugar, { unit: '1 kg', isVeg: true }),
          p('Cooking Oil', 'Canola blend cooking oil.', 2750, IMG.oil, { unit: '5 L', isVeg: true }),
          p('Banaspati Ghee', 'Vegetable ghee.', 1350, IMG.oil, { unit: '2.5 kg', isVeg: true }),
          p('Daal Chana', 'Split chickpeas.', 320, IMG.lentils, { unit: '1 kg', isVeg: true }),
          p('Daal Masoor', 'Red lentils.', 340, IMG.lentils, { unit: '1 kg', isVeg: true }),
          p('Iodised Salt', 'Table salt.', 60, IMG.sugar, { unit: '800 g', isVeg: true }),
        ],
      },
      {
        name: 'Dairy & Eggs',
        items: [
          p('Full Cream Milk', 'UHT packaged milk.', 250, IMG.milk, { unit: '1 L', isVeg: true, isPopular: true }),
          p('Farm Eggs', 'Fresh eggs.', 330, IMG.eggs, { unit: 'Dozen', isVeg: true, isPopular: true }),
          p('Yogurt (Dahi)', 'Fresh set yogurt.', 260, IMG.yogurt, { unit: '1 kg', isVeg: true }),
          p('Butter', 'Salted dairy butter.', 380, IMG.butter, { unit: '200 g', isVeg: true }),
          p('Cheddar Cheese Slices', '10 slices.', 450, IMG.cheese, { unit: '200 g', isVeg: true }),
        ],
      },
      {
        name: 'Beverages & Snacks',
        items: [
          p('Black Tea (Family Pack)', 'Premium blend tea leaves.', 1850, IMG.tea, { unit: '950 g', isVeg: true, isPopular: true }),
          p('Biscuits Family Pack', 'Assorted biscuits.', 150, IMG.biscuits, { unit: '1 pack', isVeg: true }),
          p('Potato Chips', 'Masala flavour.', 100, IMG.chips, { unit: '65 g', isVeg: true }),
          p('Soft Drink', 'Coke, Sprite or Fanta.', 200, IMG.soda, { unit: '1.5 L', isVeg: true }),
          p('Mango Juice', 'Packaged nectar.', 250, IMG.juice, { unit: '1 L', isVeg: true }),
        ],
      },
      {
        name: 'Household',
        items: [
          p('Dishwash Liquid', 'Lemon scented.', 380, IMG.detergent, { unit: '750 ml' }),
          p('Washing Powder', 'Stain remover formula.', 420, IMG.detergent, { unit: '1 kg' }),
          p('Tissue Box', '2-ply facial tissues.', 210, IMG.tissues, { unit: '150 sheets' }),
        ],
      },
    ],
  },
  {
    slug: 'sabzi-express',
    name: 'Sabzi Mandi Express',
    category: 'GROCERY',
    photo: 'photo-1540420773420-3366772f4999',
    rating: 4.5,
    ratingCount: 2870,
    deliveryTimeMin: 25,
    deliveryTimeMax: 40,
    deliveryFee: 99,
    minOrder: 500,
    distanceKm: 3.4,
    tags: ['Fruits', 'Vegetables', 'Fresh'],
    isOpen: true,
    promoLabel: 'Chaunsa season',
    area: 'Johar Town',
    address: 'Block J2, Johar Town, Lahore',
    lat: 31.466,
    lng: 74.28,
    ownerName: 'Zubair Hussain',
    ownerContact: '03001234512',
    menu: [
      {
        name: 'Vegetables',
        items: [
          p('Potatoes (Aloo)', 'Fresh local potatoes.', 90, IMG.potatoes, { unit: '1 kg', isVeg: true, isPopular: true }),
          p('Onions (Pyaz)', 'Red onions.', 110, IMG.onions, { unit: '1 kg', isVeg: true }),
          p('Tomatoes', 'Ripe and firm.', 120, IMG.tomatoes, { unit: '1 kg', isVeg: true, isPopular: true }),
          p('Green Chillies', 'Fresh hari mirch.', 40, IMG.chillies, { unit: '250 g', isVeg: true }),
          p('Ginger (Adrak)', 'Fresh ginger root.', 120, IMG.ginger, { unit: '250 g', isVeg: true }),
          p('Garlic (Lehsan)', 'Local garlic.', 110, IMG.ginger, { unit: '250 g', isVeg: true }),
          p('Spinach (Palak)', 'Fresh bunch.', 60, IMG.spinach, { unit: '1 bunch', isVeg: true }),
          p('Okra (Bhindi)', 'Tender bhindi.', 180, IMG.okra, { unit: '1 kg', isVeg: true }),
          p('Cauliflower (Gobi)', 'Whole head.', 120, IMG.cauliflower, { unit: '1 pc', isVeg: true }),
          p('Lemons', 'Juicy desi lemons.', 80, IMG.lemon, { unit: '250 g', isVeg: true }),
        ],
      },
      {
        name: 'Fruits',
        items: [
          p('Chaunsa Mangoes', 'Sweet Multani chaunsa, in season.', 280, IMG.mango, { unit: '1 kg', isVeg: true, isPopular: true }),
          p('Bananas', 'Ripe local bananas.', 160, IMG.banana, { unit: 'Dozen', isVeg: true }),
          p('Kala Kulu Apples', 'Crisp Swat apples.', 320, IMG.apple, { unit: '1 kg', isVeg: true }),
          p('Black Grapes', 'Seedless.', 250, IMG.grapes, { unit: '500 g', isVeg: true }),
          p('Guava (Amrood)', 'Fresh guavas.', 200, IMG.guava, { unit: '1 kg', isVeg: true }),
          p('Pomegranate (Anaar)', 'Kandahari anaar.', 450, IMG.pomegranate, { unit: '1 kg', isVeg: true }),
          p('Kinnow', 'Sargodha kinnow.', 200, IMG.orange, { unit: 'Dozen', isVeg: true, isPopular: true }),
          p('Watermelon', 'Whole, approx. 4 kg.', 350, IMG.watermelon, { unit: '1 pc', isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'daily-bake',
    name: 'Daily Bake House',
    category: 'GROCERY',
    photo: 'photo-1509440159596-0249088772ff',
    rating: 4.8,
    ratingCount: 1420,
    deliveryTimeMin: 15,
    deliveryTimeMax: 25,
    deliveryFee: 49,
    minOrder: 300,
    distanceKm: 1.3,
    tags: ['Bakery', 'Cakes', 'Snacks'],
    isOpen: true,
    promoLabel: 'New',
    area: 'Gulberg II',
    address: 'Hussain Chowk, Gulberg II, Lahore',
    lat: 31.518,
    lng: 74.35,
    ownerName: 'Sana Tariq',
    ownerContact: '03001234513',
    menu: [
      {
        name: 'Breads',
        items: [
          p('Sandwich Bread', 'Soft white bread.', 130, IMG.bread, { unit: 'Large loaf', isVeg: true, isPopular: true }),
          p('Brown Bread', 'Whole wheat.', 160, IMG.bread, { unit: 'Large loaf', isVeg: true }),
          p('Burger Buns (6 pcs)', 'Sesame topped.', 120, IMG.buns, { unit: 'Pack of 6', isVeg: true }),
          p('Cake Rusk', 'Crunchy tea-time rusk.', 220, IMG.rusk, { unit: '350 g', isVeg: true }),
        ],
      },
      {
        name: 'Bakery Items',
        items: [
          p('Chicken Patties', 'Flaky puff pastry with chicken filling.', 120, IMG.patties, { unit: '1 pc', isPopular: true }),
          p('Pizza Slice', 'Chicken tikka pizza slice.', 180, IMG.pizza, { unit: '1 slice' }),
          p('Cream Roll', 'Classic bakery cream roll.', 80, IMG.rusk, { unit: '1 pc', isVeg: true }),
          p('Fruit Cake Slice', 'Dense fruit cake.', 150, IMG.cake2, { unit: '1 slice', isVeg: true }),
          p('Chocolate Brownie', 'Fudgy walnut brownie.', 200, IMG.brownie, { unit: '1 pc', isVeg: true, isPopular: true }),
          p('Butter Croissant', 'Flaky and buttery.', 150, IMG.rusk, { unit: '1 pc', isVeg: true }),
        ],
      },
      {
        name: 'Cakes',
        items: [
          p('Black Forest Cake', 'Cherry and chocolate.', 1300, IMG.cake, { unit: '1 lb', isVeg: true }),
          p('Red Velvet Cake', 'Cream cheese frosting.', 1400, IMG.cake2, { unit: '1 lb', isVeg: true, isPopular: true }),
        ],
      },
      {
        name: 'Cookies',
        items: [
          p('Nankhatai', 'Traditional shortbread cookies.', 280, IMG.cookies, { unit: '250 g', isVeg: true }),
          p('Chocolate Chip Cookies', 'Soft baked.', 350, IMG.cookies, { unit: '300 g', isVeg: true }),
        ],
      },
    ],
  },
  {
    slug: 'careplus',
    name: 'CarePlus Pharmacy',
    category: 'PHARMACY',
    photo: 'photo-1585435557343-3b092031a831',
    rating: 4.7,
    ratingCount: 2540,
    deliveryTimeMin: 20,
    deliveryTimeMax: 30,
    deliveryFee: 79,
    minOrder: 300,
    distanceKm: 1.9,
    tags: ['Pharmacy', 'Wellness', 'Baby Care'],
    isOpen: true,
    promoLabel: 'Open 24/7',
    area: 'Gulberg III',
    address: 'Main Boulevard, Gulberg III, Lahore',
    lat: 31.505,
    lng: 74.35,
    ownerName: 'Dr. Ayesha Noor',
    ownerContact: '03001234514',
    menu: [
      {
        name: 'Medicine',
        items: [
          p('Paracetamol 500mg', 'Pain and fever relief.', 30, IMG.tablets, { unit: '10 tablets', isPopular: true }),
          p('Ibuprofen 400mg', 'Anti-inflammatory.', 85, IMG.medicine, { unit: '10 tablets' }),
          p('Antacid Syrup', 'Relief from acidity and heartburn.', 180, IMG.syrup, { unit: '120 ml' }),
          p('ORS Sachets', 'Oral rehydration salts.', 100, IMG.tablets, { unit: '5 sachets', isPopular: true }),
          p('Cough Syrup', 'For dry and chesty cough.', 220, IMG.syrup, { unit: '120 ml' }),
          p('Anti-Allergy Tablets', 'Non-drowsy antihistamine.', 90, IMG.tablets, { unit: '10 tablets' }),
        ],
      },
      {
        name: 'Wellness',
        items: [
          p('Vitamin C 1000mg', 'Immune support effervescent.', 350, IMG.vitamins, { unit: '20 tablets', isPopular: true }),
          p('Daily Multivitamin', 'Complete A to Z.', 650, IMG.vitamins, { unit: '30 tablets' }),
          p('Calcium + Vitamin D3', 'Bone health.', 480, IMG.tablets, { unit: '30 tablets' }),
          p('Omega-3 Fish Oil', 'Heart and brain support.', 850, IMG.omega, { unit: '30 softgels', compareAtPrice: 950 }),
        ],
      },
      {
        name: 'Personal Care',
        items: [
          p('Hand Sanitizer', '70% alcohol.', 250, IMG.sanitizer, { unit: '250 ml' }),
          p('Toothpaste', 'Fluoride whitening.', 220, IMG.toothpaste, { unit: '120 g' }),
          p('Face Masks (50 pcs)', '3-ply disposable.', 350, IMG.mask, { unit: 'Box of 50' }),
          p('Sunscreen SPF 50', 'Broad spectrum.', 950, IMG.sunscreen, { unit: '50 ml' }),
        ],
      },
      {
        name: 'Baby Care',
        items: [
          p('Diapers Size 3', 'Ultra-absorbent.', 1650, IMG.diapers, { unit: '44 count', isPopular: true }),
          p('Baby Wipes', 'Fragrance-free.', 350, IMG.wipes, { unit: '72 wipes' }),
          p('Baby Lotion', 'Gentle moisturiser.', 450, IMG.lotion, { unit: '200 ml' }),
        ],
      },
    ],
  },
  {
    slug: 'sehat-plus',
    name: 'Sehat Plus Health',
    category: 'PHARMACY',
    photo: 'photo-1584308666744-24d5c474f2ae',
    rating: 4.5,
    ratingCount: 760,
    deliveryTimeMin: 30,
    deliveryTimeMax: 40,
    deliveryFee: 99,
    minOrder: 500,
    distanceKm: 5.1,
    tags: ['Vitamins', 'Devices', 'Nutrition'],
    isOpen: true,
    area: 'Wapda Town',
    address: 'Block E2, Wapda Town, Lahore',
    lat: 31.425,
    lng: 74.265,
    ownerName: 'Dr. Umar Farooq',
    ownerContact: '03001234515',
    menu: [
      {
        name: 'Vitamins & Supplements',
        items: [
          p('Vitamin D3 2000 IU', 'Bone and immune health.', 420, IMG.vitamins, { unit: '30 softgels', isPopular: true }),
          p('Zinc 50mg', 'Immune support.', 380, IMG.tablets, { unit: '30 tablets' }),
          p('Iron + Folic Acid', 'For anaemia support.', 300, IMG.tablets, { unit: '30 tablets' }),
          p('Multivitamin for Women', 'Formulated for daily needs.', 750, IMG.vitamins, { unit: '30 tablets' }),
        ],
      },
      {
        name: 'Health Devices',
        items: [
          p('Digital Thermometer', 'Fast 10-second reading.', 650, IMG.thermometer, { unit: '1 unit' }),
          p('Blood Pressure Monitor', 'Automatic upper-arm monitor.', 4500, IMG.bpMonitor, { unit: '1 unit', isPopular: true }),
          p('Glucometer Strips', 'Compatible test strips.', 1800, IMG.glucometer, { unit: '50 strips' }),
          p('Nebulizer', 'Compressor nebulizer with mask.', 4200, IMG.nebulizer, { unit: '1 unit' }),
        ],
      },
      {
        name: 'Nutrition',
        items: [
          p('Whey Protein', 'Chocolate flavour, 24g protein per scoop.', 6500, IMG.whey, { unit: '1 kg' }),
          p('Nutritional Supplement Powder', 'Complete balanced nutrition.', 1950, IMG.whey, { unit: '400 g' }),
          p('Electrolyte Sachets', 'Hydration mix.', 250, IMG.electrolyte, { unit: '10 sachets' }),
        ],
      },
    ],
  },
  {
    slug: 'mediquick',
    name: 'MediQuick',
    category: 'PHARMACY',
    photo: 'photo-1471864190281-a93a3070b6de',
    rating: 4.4,
    ratingCount: 540,
    deliveryTimeMin: 15,
    deliveryTimeMax: 25,
    deliveryFee: 0,
    minOrder: 400,
    distanceKm: 0.9,
    tags: ['Pharmacy', 'First Aid', 'Baby Care'],
    isOpen: true,
    promoLabel: 'Free delivery',
    area: 'DHA Phase 6',
    address: 'Sector A, Commercial Area, DHA Phase 6, Lahore',
    lat: 31.48,
    lng: 74.44,
    ownerName: 'Dr. Hina Shah',
    ownerContact: '03001234516',
    menu: [
      {
        name: 'First Aid',
        items: [
          p('Adhesive Bandages', 'Assorted sizes.', 150, IMG.bandage, { unit: '20 count', isPopular: true }),
          p('Antiseptic Liquid', 'For cuts and wounds.', 180, IMG.sanitizer, { unit: '100 ml' }),
          p('Cotton Roll', 'Absorbent cotton.', 90, IMG.wipes, { unit: '100 g' }),
          p('Pain Relief Spray', 'Fast acting for muscle pain.', 450, IMG.spray, { unit: '100 ml' }),
          p('Burn Ointment', 'Soothing burn relief.', 220, IMG.lotion, { unit: '30 g' }),
        ],
      },
      {
        name: 'Medicine',
        items: [
          p('Paracetamol 500mg', 'Pain and fever relief.', 30, IMG.tablets, { unit: '10 tablets', isPopular: true }),
          p('Anti-Allergy Tablets', 'Fast relief from allergies.', 120, IMG.medicine, { unit: '10 tablets' }),
          p('Pain Relief Gel', 'Topical diclofenac gel.', 350, IMG.lotion, { unit: '50 g' }),
        ],
      },
      {
        name: 'Baby Care',
        items: [
          p('Diapers Size 4', 'Ultra-absorbent.', 1750, IMG.diapers, { unit: '40 count' }),
          p('Baby Wipes', 'Fragrance-free.', 350, IMG.wipes, { unit: '72 wipes', isPopular: true }),
          p('Baby Feeder 250ml', 'BPA-free bottle.', 350, IMG.feeder, { unit: '1 unit' }),
        ],
      },
    ],
  },
];

export const RIDERS = [
  { name: 'Muhammad Bilal', email: 'bilal.rider@quickcart.pk', phone: '03001112233', vehicleType: 'Honda CD 70', plateNumber: 'LEB 4521', status: 'APPROVED' as const, lat: 31.4907, lng: 74.3436 },
  { name: 'Usman Ali', email: 'usman.rider@quickcart.pk', phone: '03214445566', vehicleType: 'Suzuki GS 150', plateNumber: 'LEA 8830', status: 'APPROVED' as const, lat: 31.5, lng: 74.36 },
  { name: 'Hamza Sheikh', email: 'hamza.rider@quickcart.pk', phone: '03337778899', vehicleType: 'Yamaha YBR 125', plateNumber: 'LED 2207', status: 'APPROVED' as const, lat: 31.47, lng: 74.4 },
  { name: 'Ahsan Raza', email: 'ahsan.rider@quickcart.pk', phone: '03451234567', vehicleType: 'Honda CG 125', plateNumber: 'LEF 1180', status: 'PENDING' as const, lat: null, lng: null },
  { name: 'Waqas Ahmed', email: 'waqas.rider@quickcart.pk', phone: '03119876543', vehicleType: 'Electric Scooter', plateNumber: 'LEG 7745', status: 'PENDING' as const, lat: null, lng: null },
];

export const COUPONS = [
  { code: 'WELCOME20', description: '20% off your first order (up to Rs 300)', discountType: 'PERCENT' as const, discountValue: 20, maxDiscount: 300, minOrderAmount: 0, usageLimit: null },
  { code: 'FREESHIP', description: 'Free delivery on this order', discountType: 'FREE_DELIVERY' as const, discountValue: 0, maxDiscount: null, minOrderAmount: 0, usageLimit: null },
  { code: 'SAVE100', description: 'Rs 100 off orders over Rs 800', discountType: 'FLAT' as const, discountValue: 100, maxDiscount: null, minOrderAmount: 800, usageLimit: 500 },
  { code: 'BIRYANI50', description: 'Rs 50 off any order over Rs 400', discountType: 'FLAT' as const, discountValue: 50, maxDiscount: null, minOrderAmount: 400, usageLimit: 1000 },
  { code: 'JAZZ15', description: '15% off (up to Rs 250) for JazzCash users', discountType: 'PERCENT' as const, discountValue: 15, maxDiscount: 250, minOrderAmount: 0, usageLimit: null },
];

export const BANNERS = [
  { title: '20% off your first order', subtitle: 'Code WELCOME20 · up to Rs 300 · Tap to see all offers', label: 'LIMITED OFFER · LAHORE', targetType: 'OFFERS' as const, colorFrom: '#FF6B35', colorTo: '#FF8F5E', sortOrder: 0 },
  { title: 'Free delivery all weekend', subtitle: 'On every grocery order above Rs 2,000', label: 'GROCERY WEEK', targetType: 'CATEGORY' as const, targetValue: 'grocery', colorFrom: '#2EC4B6', colorTo: '#4FD8CB', sortOrder: 1 },
];

export const CATEGORIES = [
  { name: 'Restaurants', slug: 'restaurants', icon: 'restaurant-outline', type: 'store', sortOrder: 1 },
  { name: 'Grocery', slug: 'grocery', icon: 'basket-outline', type: 'store', sortOrder: 2 },
  { name: 'Pharmacy', slug: 'pharmacy', icon: 'medkit-outline', type: 'store', sortOrder: 3 },
];

export const FAQS = [
  { question: 'How do I track my order?', answer: 'Open the Orders tab and tap your active order. You will see a live map with your rider, the current status and an ETA countdown.', sortOrder: 1 },
  { question: 'Can I cancel an order?', answer: 'Orders can be cancelled free of charge until the restaurant or store starts preparing them. After that, please contact support and we will do our best to help.', sortOrder: 2 },
  { question: 'Which payment methods are accepted?', answer: 'We accept Cash on Delivery, JazzCash, Easypaisa, Visa and Mastercard debit or credit cards, and your QuickCart Wallet balance.', sortOrder: 3 },
  { question: 'How do promo codes work?', answer: 'Enter your promo code in the cart before checkout, or tap "Apply" on the Offers screen. Discounts are applied instantly and shown in the price breakdown.', sortOrder: 4 },
  { question: 'What is GST on my bill?', answer: 'Punjab Revenue Authority sales tax is applied to food and service orders as required by law. The exact amount is always shown before you place the order.', sortOrder: 5 },
  { question: 'My order arrived damaged or incomplete', answer: 'We are sorry about that. Go to the order details, tap "Need help with this order?" or contact support and we will issue a refund to your wallet or a replacement.', sortOrder: 6 },
  { question: 'Which areas of Lahore do you deliver to?', answer: 'We currently deliver across DHA, Gulberg, Model Town, Johar Town, Cavalry Ground, Wapda Town, Bahria Town and the old city. More areas are being added every month.', sortOrder: 7 },
];
